language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpcs --standard=PSR2 src
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)
